# 05_zoom_bands.py

import numpy as np
import matplotlib.pyplot as plt

from config_zgnr import LABEL_BASE


# ======================================
# Parameters you can change easily:
# ======================================
E_MIN = -3     # bottom of zoom window
E_MAX = 3       # top of zoom window
N_BELOW = 6       # number of valence bands to show below EF
N_ABOVE = 6       # number of conduction bands to show above EF
# ======================================


def main():
    # Load the band data generated by 02_bands_dos_zgnr.py
    data = np.load(f"{LABEL_BASE}_bands_dos.npz")
    k_dimless = data["k_dimless"]
    E_rel_all = data["E_rel_all"]   # (nk, nbands)

    nk, nbands = E_rel_all.shape

    # Determine the index of the highest valence band at Γ (k=0)
    vals_at_gamma = E_rel_all[0, :]
    i_valence = np.where(vals_at_gamma < 0)[0].max()

    # Select band range to plot
    i_min = max(i_valence - N_BELOW + 1, 0)
    i_max = min(i_valence + N_ABOVE + 1, nbands)

    print(f"Plotting bands {i_min} to {i_max-1} (zoom window {E_MIN} to {E_MAX} eV)")

    # Plot
    fig, ax = plt.subplots(figsize=(6, 5))

    for n in range(i_min, i_max):
        ax.plot(k_dimless / np.pi, E_rel_all[:, n], lw=1)

    ax.axhline(0, ls="--", lw=0.6, color="k")
    ax.set_ylim(E_MIN, E_MAX)
    ax.set_xlim(0, 1)
    ax.set_xlabel(r"$k a / \pi$")
    ax.set_ylabel("Energy (eV)")
    ax.set_title(f"Zoomed band structure\n{LABEL_BASE}")

    plt.tight_layout()
    plt.savefig(f"{LABEL_BASE}_bands_zoom.png", dpi=200)
    plt.show()

    print(f"Saved zoomed bands to {LABEL_BASE}_bands_zoom.png")


if __name__ == "__main__":
    main()
